### ISSUE TITLE
Add Canva Whiteboard

### ISSUE THREAD

**Issue by kDCYorke** [museapphq/infinitecanvas.tools#136]
https://www.canva.com/online-whiteboard/

From the above website:

Canva Whiteboards gives you infinite space to collaborate. Brainstorm, run a strategy session, or plan out a project. It's never been easier — or more fun — to work together. Capture your team’s best ideas and turn them into action plans in an instant with AI tools.

**Comment by abstractalgo** [comment]
Possible duplicate of https://github.com/museapphq/infinitecanvas.tools/issues/116.

**Comment by kDCYorke** [comment]
Apologies!
